// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'Card': typeof import("../components/Card..vue")['default'],
    'Cart': typeof import("../components/Cart.vue")['default'],
    'CheckoutForm': typeof import("../components/CheckoutForm.vue")['default'],
    'Courses': typeof import("../components/courses.vue")['default'],
    'CustomButton': typeof import("../components/CustomButton.vue")['default'],
    'DHeader': typeof import("../components/DHeader.vue")['default'],
    'DNav': typeof import("../components/DNav.vue")['default'],
    'HInput': typeof import("../components/HInput.vue")['default'],
    'HModal': typeof import("../components/HModal.vue")['default'],
    'SuccessScreen': typeof import("../components/SuccessScreen.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyCard': typeof import("../components/Card..vue")['default'],
    'LazyCart': typeof import("../components/Cart.vue")['default'],
    'LazyCheckoutForm': typeof import("../components/CheckoutForm.vue")['default'],
    'LazyCourses': typeof import("../components/courses.vue")['default'],
    'LazyCustomButton': typeof import("../components/CustomButton.vue")['default'],
    'LazyDHeader': typeof import("../components/DHeader.vue")['default'],
    'LazyDNav': typeof import("../components/DNav.vue")['default'],
    'LazyHInput': typeof import("../components/HInput.vue")['default'],
    'LazyHModal': typeof import("../components/HModal.vue")['default'],
    'LazySuccessScreen': typeof import("../components/SuccessScreen.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  }
}
export const Card: typeof import("../components/Card..vue")['default']
export const Cart: typeof import("../components/Cart.vue")['default']
export const CheckoutForm: typeof import("../components/CheckoutForm.vue")['default']
export const Courses: typeof import("../components/courses.vue")['default']
export const CustomButton: typeof import("../components/CustomButton.vue")['default']
export const DHeader: typeof import("../components/DHeader.vue")['default']
export const DNav: typeof import("../components/DNav.vue")['default']
export const HInput: typeof import("../components/HInput.vue")['default']
export const HModal: typeof import("../components/HModal.vue")['default']
export const SuccessScreen: typeof import("../components/SuccessScreen.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyCard: typeof import("../components/Card..vue")['default']
export const LazyCart: typeof import("../components/Cart.vue")['default']
export const LazyCheckoutForm: typeof import("../components/CheckoutForm.vue")['default']
export const LazyCourses: typeof import("../components/courses.vue")['default']
export const LazyCustomButton: typeof import("../components/CustomButton.vue")['default']
export const LazyDHeader: typeof import("../components/DHeader.vue")['default']
export const LazyDNav: typeof import("../components/DNav.vue")['default']
export const LazyHInput: typeof import("../components/HInput.vue")['default']
export const LazyHModal: typeof import("../components/HModal.vue")['default']
export const LazySuccessScreen: typeof import("../components/SuccessScreen.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const componentNames: string[]
